### ISSUE TITLE
Certain snippets throw an error

### ISSUE THREAD

**Issue by scottksmith95** [lukabratos/Snippet#1]
I think it may have to do with code that contains braces { or }

When I try to save code that has braces, I get the following error message:

The action “Run Shell Script” encountered an error.

Here is the code I am testing with:

```
static void Main() 
{
    Console.WriteLine("Hello World!");

    // Keep the console window open in debug mode.
    Console.WriteLine("Press any key to exit.");
    Console.ReadKey();
}
```

**Comment by lukabratos** [comment]
I have tested and it is working: https://gist.github.com/9decf2063830369f46b9

**Comment by lukabratos** [comment]
Hi @scottksmith95!
Snippet was rewritten in Python by @ncanceill because of [this](https://github.com/lukabratos/Snippet/issues/2).
You can download the latest version and I hope that it will fix the error!
