### ISSUE TITLE
Ruby does not handle UTF-8 from Automator

### ISSUE THREAD

**Issue by ncanceill** [lukabratos/Snippet#2]
### How to reproduce

Use the Snippet service on an UTF-8 string like `ƒ`, and the following error is thrown:

**The action “Execute a Shell script” encountered an error.**
### The catch

The behavior is _related to Automator_, because directly using the Ruby script works — _eg_ `ruby snippet.rb ƒ`. Maybe this is related to #1.
### The fix

Using Python instead of Ruby fixes it. Will submit PR in a few moments. Points:
- By default, Mac OS X is distributed with Python 2 linked to `/usr/bin/python`.
- Automator can execute Python scripts as easily as Ruby.

**Comment by ncanceill** [comment]
I proposed a PR: see #3.

**Comment by lukabratos** [comment]
I was able to reproduce this error. Your points are valid and I agree with you!
